### ISSUE TITLE
Unable to change the value of boolean inputs when running FMUs under FMU-Proxy.

### ISSUE THREAD

**Issue by THEvang** [NTNU-IHB/FMU-proxy#131]
I run a setup using the Cosim demo app together with FMU-Proxy version 0.6.2.

The FMUs are hosted in an Nginx docker container and served to another container running the Cosim demo app through http.
FMU-proxy runs in a third docker container. 

However, when running this setup I am not able to change the value of boolean inputs to the FMUs, and some boolean values are flickering between true and false. 

I have confirmed that the same setup works when running the FMUs directly in the same container as the Cosim demo app.

**Comment by markaren** [comment]
I think the best solution to this issue is to migrate to a cosim version with [proxy-fmu](https://github.com/open-simulation-platform/proxy-fmu) support https://github.com/open-simulation-platform/libcosim/pull/633. I think the OSP can be quick about releasing a new version once the (approved) PR is merged.

The FMU-proxy version represented by 0.6.2 is pretty much only kept around for legacy reasons (integration with osp), but now proxy-fmu is replacing it. As you might know, the _current_ use case for FMU-proxy is to act as a tool-independent drop-in replacement for existing FMUs.
